// <auto-generated />
namespace LojinhaEcoomerce.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Mudancasnatabeladeprodutos : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Mudancasnatabeladeprodutos));
        
        string IMigrationMetadata.Id
        {
            get { return "201803311835581_Mudancas na tabela de produtos"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
