// <auto-generated />
namespace LojinhaEcoomerce.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Adicaodetabelasdomeuprojetinhonobancolojinha : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Adicaodetabelasdomeuprojetinhonobancolojinha));
        
        string IMigrationMetadata.Id
        {
            get { return "201804022307206_Adicao de tabelas do meu projetinho no banco lojinha"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
